// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/domains/auth"
)

// Injectors from wire.go:

func controllers() (apiHandlers, error) {
	authController := auth.NewAuthController()
	mainApiHandlers := newApiHandlers(authController)
	return mainApiHandlers, nil
}

// wire.go:

type apiHandlers struct {
	AuthC *auth.AuthController
}

func newApiHandlers(
	authC *auth.AuthController,
) apiHandlers {
	return apiHandlers{
		AuthC: authC,
	}
}
