// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/domains/auth"
	"app/domains/user"
	"app/sql/db"
	"github.com/go-chi/jwtauth"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func controllers(jwtAuth *jwtauth.JWTAuth, queries *db.Queries) (reqControllers, error) {
	userRepo := user.NewUserRepo(queries)
	userService := user.NewUserService(userRepo)
	authService := auth.NewAuthService(jwtAuth, userService)
	controller := auth.NewAuthController(jwtAuth, authService, userService)
	userController := user.NewUserController(userService)
	mainReqControllers := newReqControllers(controller, userController)
	return mainReqControllers, nil
}

// wire.go:

type reqControllers struct {
	AuthC *auth.Controller
	AccC  *user.UserController
}

func newReqControllers(
	authC *auth.Controller,
	accC *user.UserController,
) reqControllers {
	return reqControllers{
		AuthC: authC,
	}
}
