// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/domains/auth"
)

// Injectors from wire.go:

func controllers() (reqControllers, error) {
	authController := auth.NewAuthController()
	mainReqControllers := newReqControllers(authController)
	return mainReqControllers, nil
}

// wire.go:

type reqControllers struct {
	AuthC *auth.Controller
}

func newReqControllers(
	authC *auth.Controller,
) reqControllers {
	return reqControllers{
		AuthC: authC,
	}
}
