// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Account struct {
	AccountID int64  `json:"account_id"`
	Name      string `json:"name"`
	Level     int16  `json:"level"`
	Email     string `json:"email"`
}
