// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Account struct {
	Accountid int64          `json:"accountid"`
	Name      sql.NullString `json:"name"`
	Password  string         `json:"password"`
	Level     sql.NullInt32  `json:"level"`
	Email     sql.NullString `json:"email"`
}
