// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Account struct {
	Accountid int64  `json:"accountid"`
	Name      string `json:"name"`
	Level     int32  `json:"level"`
	Email     string `json:"email"`
}
